-- Create migration generated by prisma migrate diff --from-empty --to-schema-datamodel
-- Name: add_closet_outfit_fields

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "public"."USER_STATUS" AS ENUM ('UNVERIFIED', 'VERIFIED', 'BANNED');     

-- CreateEnum
CREATE TYPE "public"."USER_ROLE" AS ENUM ('USER', 'MOD', 'ADMIN');

-- CreateEnum
CREATE TYPE "public"."SHOP_STATUS" AS ENUM ('UNVERIFIED', 'VERIFIED', 'SUSPENDED');  

-- CreateEnum
CREATE TYPE "public"."SHOP_ROLE" AS ENUM ('STAFF', 'OWNER');

-- CreateEnum
CREATE TYPE "public"."SHOP_STAFF_STATUS" AS ENUM ('ACTIVE', 'REMOVED');

-- CreateEnum
CREATE TYPE "public"."PRODUCT_TYPE" AS ENUM ('SALE', 'RENT');

-- CreateEnum
CREATE TYPE "public"."PRODUCT_PRICING_STATUS" AS ENUM ('INACTIVE', 'ACTIVE');        

-- CreateEnum
CREATE TYPE "public"."PRODUCT_STATUS" AS ENUM ('INACTIVE', 'ACTIVE');

-- CreateEnum
CREATE TYPE "public"."FILTER_STATUS" AS ENUM ('INACTIVE', 'ACTIVE');

-- CreateEnum
CREATE TYPE "public"."PAYMENT_METHOD" AS ENUM ('BANK_TRANSFER', 'COD');

-- CreateEnum
CREATE TYPE "public"."ORDER_TYPE" AS ENUM ('SALE', 'RENT');

-- CreateEnum
CREATE TYPE "public"."ORDER_STATUS" AS ENUM ('PENDING', 'DELIVERING', 'DELIVERED', 'CANCELED', 'RETURNED', 'SUCCESS');                                                    
-- CreateEnum
CREATE TYPE "public"."TRANSACTION_STATUS" AS ENUM ('PENDING', 'CANCELLED', 'UNDERPAID', 'PAID', 'EXPIRED', 'PROCESSING', 'FAILED');                                       
-- CreateEnum
CREATE TYPE "public"."TRANSACTION_TYPE" AS ENUM ('PAYIN', 'PAYOUT');

-- CreateEnum
CREATE TYPE "public"."SUBSCRIPTION_ORDER_STATUS" AS ENUM ('PENDING', 'PAID', 'CANCELED');                                                                                 
-- CreateEnum
CREATE TYPE "public"."SUBSCRIPTION_PLAN_STATUS" AS ENUM ('INACTIVE', 'ACTIVE');      

-- CreateEnum
CREATE TYPE "public"."USER_SUBSCRIPTION_STATUS" AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELED');                                                                                
-- CreateEnum
CREATE TYPE "public"."CLOSET_ITEM_TYPE" AS ENUM ('TOPS', 'OUTWEAR', 'BOTTOMS', 'ACCESSORIES');                                                                            
-- CreateTable
CREATE TABLE "public"."users" (
    "id" TEXT NOT NULL,
    "username" TEXT,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "avatar" TEXT,
    "bio" TEXT,
    "phone_number" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "status" "public"."USER_STATUS" NOT NULL DEFAULT 'UNVERIFIED',
    "role" "public"."USER_ROLE" NOT NULL DEFAULT 'USER',
    "subscription_plan_id" TEXT,
    "subscription_plan_start_date" TIMESTAMP(3),
    "subscription_plan_end_date" TIMESTAMP(3),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."addresses" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "receiver_name" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "province_id" INTEGER NOT NULL,
    "ward_id" INTEGER NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "addresses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."sessions" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."shops" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "address" TEXT NOT NULL,
    "phone_number" TEXT,
    "email" TEXT,
    "avatar" TEXT,
    "background" TEXT,
    "rating" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "status" "public"."SHOP_STATUS" NOT NULL DEFAULT 'UNVERIFIED',

    CONSTRAINT "shops_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."shop_staffs" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "shop_id" TEXT NOT NULL,
    "joined_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "notes" TEXT,
    "role" "public"."SHOP_ROLE" NOT NULL DEFAULT 'STAFF',
    "status" "public"."SHOP_STAFF_STATUS" NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "shop_staffs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."products" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "shop_id" TEXT NOT NULL,
    "status" "public"."PRODUCT_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "type" "public"."PRODUCT_TYPE" NOT NULL,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."variants" (
    "id" TEXT NOT NULL,
    "product_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "stock" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "status" "public"."PRODUCT_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "images" TEXT[],

    CONSTRAINT "variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."product_pricings" (
    "id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "start_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "end_date" TIMESTAMP(3),
    "status" "public"."PRODUCT_PRICING_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_pricings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."filters" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" "public"."FILTER_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "filters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."filter_props" (
    "id" TEXT NOT NULL,
    "filter_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "status" "public"."FILTER_STATUS" NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "filter_props_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."product_by_filter_props" (
    "id" TEXT NOT NULL,
    "product_id" TEXT NOT NULL,
    "filter_prop_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "product_by_filter_props_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."orders" (
    "id" TEXT NOT NULL,
    "order_code" INTEGER NOT NULL,
    "user_id" TEXT NOT NULL,
    "total_value" DOUBLE PRECISION NOT NULL,
    "discount_value" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "final_value" DOUBLE PRECISION NOT NULL,
    "payment_method" "public"."PAYMENT_METHOD" NOT NULL,
    "type" "public"."ORDER_TYPE" NOT NULL,
    "receiver_name" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "province_id" INTEGER NOT NULL,
    "ward_id" INTEGER NOT NULL,
    "status" "public"."ORDER_STATUS" NOT NULL DEFAULT 'PENDING',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."order_details" (
    "id" TEXT NOT NULL,
    "order_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "discount_value" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "rental_start_date" TIMESTAMP(3),
    "rental_end_date" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "order_details_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."subscription_plans" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "price" DOUBLE PRECISION NOT NULL,
    "duration_days" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "status" "public"."SUBSCRIPTION_PLAN_STATUS" NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "subscription_plans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."subscription_orders" (
    "id" TEXT NOT NULL,
    "subscription_plan_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "payment_method" "public"."PAYMENT_METHOD" NOT NULL DEFAULT 'BANK_TRANSFER',     
    "status" "public"."SUBSCRIPTION_ORDER_STATUS" NOT NULL DEFAULT 'PENDING',        
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "order_code" INTEGER NOT NULL,

    CONSTRAINT "subscription_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."transactions" (
    "id" TEXT NOT NULL,
    "ammount" DOUBLE PRECISION NOT NULL,
    "description" TEXT,
    "type" "public"."TRANSACTION_TYPE" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "order_id" TEXT,
    "status" "public"."TRANSACTION_STATUS" NOT NULL,
    "subscription_order_id" TEXT,

    CONSTRAINT "transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."posts" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "author_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "published" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."reacts" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "post_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "reacts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."comments" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "post_id" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "quote_comment_id" TEXT,

    CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."closet_items" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "public"."CLOSET_ITEM_TYPE" NOT NULL,
    "image" TEXT NOT NULL,
    "color_palette" TEXT,
    "material" TEXT,
    "style_tag" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "closet_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."outfits" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "name" TEXT,
    "style" TEXT,
    "occasion" TEXT,
    "season" TEXT,
    "color_theme" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "top_id" TEXT,
    "outwear_id" TEXT,
    "bottom_id" TEXT,

    CONSTRAINT "outfits_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."_UserSubscriptionPlan" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_UserSubscriptionPlan_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "public"."_OutfitAccessories" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_OutfitAccessories_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "public"."users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "public"."users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_hash_key" ON "public"."sessions"("hash");

-- CreateIndex
CREATE UNIQUE INDEX "filters_name_key" ON "public"."filters"("name");

-- CreateIndex
CREATE UNIQUE INDEX "orders_order_code_key" ON "public"."orders"("order_code");      

-- CreateIndex
CREATE UNIQUE INDEX "subscription_orders_order_code_key" ON "public"."subscription_orders"("order_code");                                                                 
-- CreateIndex
CREATE INDEX "_UserSubscriptionPlan_B_index" ON "public"."_UserSubscriptionPlan"("B");                                                                                   
-- CreateIndex
CREATE INDEX "_OutfitAccessories_B_index" ON "public"."_OutfitAccessories"("B");     

-- AddForeignKey
ALTER TABLE "public"."users" ADD CONSTRAINT "users_subscription_plan_id_fkey" FOREIGN KEY ("subscription_plan_id") REFERENCES "public"."subscription_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;                                                        
-- AddForeignKey
ALTER TABLE "public"."addresses" ADD CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;  
-- AddForeignKey
ALTER TABLE "public"."sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;    
-- AddForeignKey
ALTER TABLE "public"."shop_staffs" ADD CONSTRAINT "shop_staffs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                                   
-- AddForeignKey
ALTER TABLE "public"."shop_staffs" ADD CONSTRAINT "shop_staffs_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                                   
-- AddForeignKey
ALTER TABLE "public"."products" ADD CONSTRAINT "products_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE RESTRICT ON UPDATE CASCADE;    
-- AddForeignKey
ALTER TABLE "public"."variants" ADD CONSTRAINT "variants_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                                
-- AddForeignKey
ALTER TABLE "public"."product_pricings" ADD CONSTRAINT "product_pricings_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                
-- AddForeignKey
ALTER TABLE "public"."filter_props" ADD CONSTRAINT "filter_props_filter_id_fkey" FOREIGN KEY ("filter_id") REFERENCES "public"."filters"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                            
-- AddForeignKey
ALTER TABLE "public"."product_by_filter_props" ADD CONSTRAINT "product_by_filter_props_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                  
-- AddForeignKey
ALTER TABLE "public"."product_by_filter_props" ADD CONSTRAINT "product_by_filter_props_filter_prop_id_fkey" FOREIGN KEY ("filter_prop_id") REFERENCES "public"."filter_props"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                      
-- AddForeignKey
ALTER TABLE "public"."order_details" ADD CONSTRAINT "order_details_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                            
-- AddForeignKey
ALTER TABLE "public"."order_details" ADD CONSTRAINT "order_details_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                      
-- AddForeignKey
ALTER TABLE "public"."transactions" ADD CONSTRAINT "transactions_subscription_order_id_fkey" FOREIGN KEY ("subscription_order_id") REFERENCES "public"."subscription_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;                                        
-- AddForeignKey
ALTER TABLE "public"."transactions" ADD CONSTRAINT "transactions_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;                                                                              
-- AddForeignKey
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;      
-- AddForeignKey
ALTER TABLE "public"."reacts" ADD CONSTRAINT "reacts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;        
-- AddForeignKey
ALTER TABLE "public"."reacts" ADD CONSTRAINT "reacts_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;        
-- AddForeignKey
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;    
-- AddForeignKey
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;    
-- AddForeignKey
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_quote_comment_id_fkey" FOREIGN KEY ("quote_comment_id") REFERENCES "public"."comments"("id") ON DELETE SET NULL ON UPDATE CASCADE;                                                                    
-- AddForeignKey
ALTER TABLE "public"."closet_items" ADD CONSTRAINT "closet_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;                                                                                
-- AddForeignKey
ALTER TABLE "public"."outfits" ADD CONSTRAINT "outfits_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;      
-- AddForeignKey
ALTER TABLE "public"."outfits" ADD CONSTRAINT "outfits_top_id_fkey" FOREIGN KEY ("top_id") REFERENCES "public"."closet_items"("id") ON DELETE SET NULL ON UPDATE CASCADE; 
-- AddForeignKey
ALTER TABLE "public"."outfits" ADD CONSTRAINT "outfits_outwear_id_fkey" FOREIGN KEY ("outwear_id") REFERENCES "public"."closet_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;                                                                              
-- AddForeignKey
ALTER TABLE "public"."outfits" ADD CONSTRAINT "outfits_bottom_id_fkey" FOREIGN KEY ("bottom_id") REFERENCES "public"."closet_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;                                                                                
-- AddForeignKey
ALTER TABLE "public"."_UserSubscriptionPlan" ADD CONSTRAINT "_UserSubscriptionPlan_A_fkey" FOREIGN KEY ("A") REFERENCES "public"."subscription_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;                                                               
-- AddForeignKey
ALTER TABLE "public"."_UserSubscriptionPlan" ADD CONSTRAINT "_UserSubscriptionPlan_B_fkey" FOREIGN KEY ("B") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;                                                                            
-- AddForeignKey
ALTER TABLE "public"."_OutfitAccessories" ADD CONSTRAINT "_OutfitAccessories_A_fkey" FOREIGN KEY ("A") REFERENCES "public"."closet_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;                                                                            
-- AddForeignKey
ALTER TABLE "public"."_OutfitAccessories" ADD CONSTRAINT "_OutfitAccessories_B_fkey" FOREIGN KEY ("B") REFERENCES "public"."outfits"("id") ON DELETE CASCADE ON UPDATE CASCADE;                                                                                
